### PR TITLE
Bug 1974477: Disable insecure global id if no insecure clients

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
In the latest Ceph releases starting with v16.2.1, all clients are recommended to be updated so they will have a security fix to connect with a secure global ID. A health warning will be raised if any insecure clients are connected and another health warning is raised if insecure clients are still allowed. Rook will now disable allowing the insecure clients if the health warning is not being raised to indicate that there are insecure clients still connected. This means that upgraded clusters will not have this disabled until all the daemons are updated.

**Which issue is resolved by this Pull Request:**
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1974477

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
Waiting for BZ approval...

**Comment by leseb** [comment]
> Waiting for BZ approval...

Converted to draft based on that.

**Comment by agarwal-mudit** [comment]
BZ is approved now

**Comment by obnoxxx** [comment]
@leseb - I think this needs the `approved` label to merge. Is anything pending?

**Comment by leseb** [comment]
> @leseb - I think this needs the `approved` label to merge. Is anything pending?

No I was just waiting for the CI :)

**Comment by obnoxxx** [comment]
> > @leseb - I think this needs the `approved` label to merge. Is anything pending?
> 
> No I was just waiting for the CI :)

Ah! 👍

**Pull request merged**
