### PR TITLE
Bug 1966139: revert the slow ops alert fix

### PR DESCRIPTION
**Pull request by agarwal-mudit**
This reverts commit 08bbdc7ccefe4572fa512c93d79d9f33d5c1ff93.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
/retitle Bug 1966139: revert the slow ops alert fix

**Review by leseb — CHANGES_REQUESTED** [review]
When reverting a commit you must explain why.

**Comment by agarwal-mudit** [comment]
> When reverting a commit you must explain why.

Sure, as part of commit message or as a PR comment?

**Comment by leseb** [comment]
> > When reverting a commit you must explain why.
> 
> Sure, as part of commit message or as a PR comment?

Commit message.

**Comment by obnoxxx** [comment]
> > When reverting a commit you must explain why.
> 
> Sure, as part of commit message or as a PR comment?

I'd say ideally both. But at the least in the commit message. - my 2 cents

**Comment by leseb** [comment]
> > > When reverting a commit you must explain why.
> > 
> > 
> > Sure, as part of commit message or as a PR comment?
> 
> I'd say ideally both. But at the least in the commit message. - my 2 cents

If it's in the commit message it'd be reflected automatically in the PR ;-)

**Comment by agarwal-mudit** [comment]
> If it's in the commit message it'd be reflected automatically in the PR ;-)

Done now, was asking because there is no technical reason for reverting this :)

**Comment by obnoxxx** [comment]
> > > > When reverting a commit you must explain why.
> > > 
> > > 
> > > Sure, as part of commit message or as a PR comment?
> > 
> > 
> > I'd say ideally both. But at the least in the commit message. - my 2 cents
> 
> If it's in the commit message it'd be reflected automatically in the PR ;-)

If it is a single commit PR, yes. :-)

**Review by obnoxxx — APPROVED** [review]
lgtm

**Review by leseb — APPROVED** [review]

**Pull request merged**
